api/urls.py
from django.conf.urls import include, url
from api.controllers import statistic, user

urlpatterns = [
    url(r'^statistic/post$', statistic.post_data),
    url(r'^statistic/bandwidth$', statistic.user_bandwidth),
    url(r'^statistic/connection$', statistic.user_connection),
    url(r'^statistic/server_bandwidth$', statistic.server_bandwidth),
]

urlpatterns += [
    url(r'^user/config$', user.config),
]

mussui/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include('sysadmin.urls')),
    url(r'^', include('portal.urls')),
]

sysadmin/urls.py
from django.conf.urls import include, url
from sysadmin.controllers import login, user, server, download, license, operation_log

urlpatterns = [
    # Login
    url(r'^/?$', login.index),
    url(r'^total_bandwidth$', login.total_bandwidth),
    url(r'^login$', login.login_index),
    url(r'^do_login$', login.do_login),
    url(r'^logout$', login.do_logout),
    url(r'^change_password$', login.change_password),
]

urlpatterns += [
    # User admin
    url(r"^customers/?$", user.index),
    url(r"^customers/create$", user.create),
    url(r"^customers/(?P<id>\d+)$", user.details),
    url(r"^customers/(?P<id>\d+)/config$", user.config),
    url(r"^customers/(?P<id>\d+)/edit$", user.edit),
    url(r"^customers/(?P<id>\d+)/enable$", user.enable),
    url(r"^customers/(?P<id>\d+)/disable$", user.disable),
    url(r"^customers/(?P<id>\d+)/delete$", user.delete),
]

urlpatterns += [
    # User admin
    url(r"^servers/?$", server.index),
    url(r"^servers/create$", server.create),
    url(r"^servers/(?P<id>\d+)$", server.detail),
    url(r"^servers/(?P<id>\d+)/edit$", server.edit),
    url(r"^servers/(?P<id>\d+)/delete$", server.delete),
]

urlpatterns += [
    url(r'^download/?$', download.index),
]

urlpatterns += [
    url(r'^license/?$', license.index),
    url(r'^license/update$', license.update),
]

urlpatterns += [
    url(r'^operation_log/?$', operation_log.index),
]

db/models.py
import rsa
import json
import redis
import base64
import random
import logging
import hashlib
from uuid import getnode
from datetime import datetime
from django.db import models
from mussui import config


def generate_user_id(start=1000, end=99000):
    for i in range(10):
        uid = random.randrange(start, end)
        if SSUser.objects.filter(userid=uid).count() <= 0:
            return uid
    return None


def load_public_key():
    pk = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA11LzgDq5c2Ts3eSQ95wvt6Lqm5KT86X81ofTD23mZYoStX7qg4Qu
TeT3UOrjcMzGJ/zFSkU0d+A9My5zlp4fN+wozuOXQHo/bbMDG46s2fMkHxT/h+kY
sXUfJIURJ12N1FaSOhCSToIHCr9jbm7aQgECqPHTTQz1chl3BA2ggDPkD16gHxc1
Up2a6GbONE5o0h/OpFsT3qJueNR2gYfkACiBONj2yY6YINyMgKDrKvcY5/nmi5zg
HOKYis4QzQ4f3HmUyKfCrRkvWa0e+rZL6/nl0zcSk2338+zDV7zxkRa/iXxaDMee
LclgkDFsEMY/3Ytfeiiz0mV4nqKdUMsAfQIDAQAB
-----END RSA PUBLIC KEY-----"""
    return rsa.PublicKey.load_pkcs1(pk)


__REDIS_CONN_POOL__ = None


def get_redis_connection():
    global __REDIS_CONN_POOL__
    if not config.REDIS['use']:
        return None
    if __REDIS_CONN_POOL__ is None:
        pool = redis.ConnectionPool(
            max_connections=100,
            host=config.REDIS['host'],
            port=config.REDIS['port'],
            db=config.REDIS['db']
        )
        __REDIS_CONN_POOL__ = pool
    return redis.Redis(connection_pool=__REDIS_CONN_POOL__)


def clean_cache(userid):
    try:
        conn = get_redis_connection()
        if conn is None:
            return
        conn.delete(str(userid))
    except Exception as e:
        logging.exception(e)


class SSUser(models.Model):
    STATUS = ['Enabled', 'Disabled']
    name = models.CharField(max_length=255, null=False, db_index=True, unique=True)
    userid = models.IntegerField(null=False, db_index=True)
    password = models.CharField(max_length=255, null=False)
    status = models.CharField(max_length=20, null=False, default="Enabled")
    bandwidth = models.IntegerField(null=False, default=2)
    created_at = models.DateTimeField(auto_now_add=True)
    servers_cache = models.CharField(max_length=1024, null=False, default="")
    number_server = models.IntegerField(null=False, default=1)
    login_password = models.CharField(max_length=255, null=False, default="")
    expire_date = models.DateTimeField(null=True)
    servers = models.ManyToManyField("Server")

    class Meta:
        db_table = "user"

    @classmethod
    def create(cls, name, servers, bandwidth, password, expire=None):
        query = SSUser.objects.filter(name=name)
        if query.count() > 0:
            raise Exception("Name already exists")
        uid = generate_user_id()
        if uid is None:
            raise Exception("Cannot generate userid")
        user = SSUser(userid=uid, name=name, status=SSUser.STATUS[0], number_server=servers, bandwidth=bandwidth, expire_date=expire)
        user.generate_password()
        user.set_password(password, False)
        user.save()
        user.auto_assign_servers()
        return user

    @classmethod
    def get_by_name(cls, username):
        query = SSUser.objects.filter(name=username, status="Enabled")
        if len(query) == 0:
            return None
        return query[0]

    @classmethod
    def authorization(cls, username, password):
        hpassword = hashlib.sha256(password).hexdigest()
        users = SSUser.objects.filter(name=username, status="Enabled", login_password=hpassword)
        if len(users) == 0:
            return None
        return users[0]

    def get_expire_str(self):
        if self.expire_date is None:
            return ""
        return self.expire_date.strftime("%Y-%m-%d")

    def is_expire(self):
        if self.expire_date is None:
            return False
        now = datetime.now()
        return now > self.expire_date

    def server_ids(self):
        return ",".join([str(server.id) for server in self.servers.all()])

    def replace_servers(self, new_servers):
        self_servers = [s.id for s in self.servers.all()]
        need_replace = False
        if len(new_servers) == len(self_servers):
            for ns in new_servers:
                if ns.id not in self_servers:
                    need_replace = True
                    break
        else:
            need_replace = True
        if need_replace:
            self.servers.clear()
            for ns in new_servers:
                self.servers.add(ns)

    def set_password(self, password, save=True):
        h = hashlib.sha256(password)
        self.login_password = h.hexdigest()
        if save:
            self.save()

    # Override save method
    def save(self):
        super(SSUser, self).save()
        clean_cache(self.userid)

    def generate_password(self):
        seed = "%s-%s" % (str(datetime.now()), self.userid)
        h = hashlib.md5(seed)
        self.password = h.hexdigest()

    def enable(self):
        self.status = SSUser.STATUS[0]
        self.save()

    def disable(self):
        self.status = SSUser.STATUS[1]
        self.save()

    def auto_assign_servers(self):
        self.servers.clear()
        servers = list(Server.objects.filter(status="Enabled"))
        ret = set()
        loop_times = min(self.number_server, len(servers))
        random.shuffle(servers)
        for i in range(loop_times):
            server = servers[i]
            self.servers.add(server)

    def get_servers(self):
        if self.servers.count() == 0:
            self.auto_assign_servers()
        query = self.servers.filter(status__in=['Enabled', 'Full'])
        ret = []
        for server in query:
            ret.append([server.hostname, "%s:%s" % (server.ip, server.port), "%s-auth" % server.encryption])
        return ret

    def servers_str(self):
        return "<br/>".join(["%s" % (i[0]) for i in self.get_servers()])

    def generate_config(self):
        server_password = []
        for server in self.get_servers():
            item = [server[1], self.password, server[2]]
            server_password.append(item)
        cfg_data = {
            "local_port": 7070,
            "auth": True,
            "user_id": self.userid,
            "server_password": server_password,
        }
        return json.dumps(cfg_data, indent=4, sort_keys=True)


class Server(models.Model):
    ENCRYPTION_METHODS = [
        'aes-128-cfb',
        'aes-192-cfb',
        'aes-256-cfb',
        'rc4-md5',
    ]
    STATUS = [
        'Enabled',
        'Disabled',
        'Full',
    ]
    hostname = models.CharField(max_length=255, null=False, db_index=True, unique=True)
    ip = models.GenericIPAddressField(null=False)
    port = models.IntegerField(null=False, default=8387)
    status = models.CharField(max_length=20, null=False, default="Enabled")
    encryption = models.CharField(max_length=50, null=False, default="aes-128-cfb")
    comments = models.TextField(null=False, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)


class License(models.Model):
    fingerprint = models.CharField(max_length=255, null=False)
    license = models.TextField(null=True, blank=True, default="")

    @classmethod
    def initial(cls):
        query = License.objects.all()
        if len(query) != 0:
            l = query[0]
            if l.fingerprint != "":
                return
        license = License(fingerprint="")
        license.check_finger_print()
        license.save()
        return license

    @classmethod
    def get_or_init(cls):
        license = License.get()
        if license is None:
            license = License.initial()
        return license

    @classmethod
    def get(cls):
        query = License.objects.all()
        if len(query) > 0:
            license = query[0]
            license.check_finger_print()
            return license
        return None

    def check_finger_print(self):
        finger_print = hashlib.sha1(str(getnode())).hexdigest()
        if self.fingerprint == "":
            self.fingerprint = finger_print
        else:
            if self.fingerprint != finger_print:
                self.fingerprint = finger_print
                self.save()

    def __load_config(self, data):
        ret = {}
        pairs = data.split("|")
        for pair in pairs:
            kvpair = pair.split(":")
            if len(kvpair) != 2:
                continue
            key, value = kvpair
            ret[key] = value
        return ret

    def get_config(self):
        try:
            data = self.__load_config(base64.decodestring(self.license))
            pconf, sign = base64.decodestring(data['config']), base64.decodestring(data['sign'])
            pubkey = load_public_key()
            verify = rsa.verify(pconf + self.fingerprint, sign, pubkey)
            if verify:
                return self.__load_config(pconf)
        except Exception as e:
            pass
        return None

    def enable_unlimited_bandwidth(self):
        ubcfg = int(self.get_config().get("unlimited", 0))
        return ubcfg == 1

    def expired(self):
        cfg = self.get_config()
        if cfg is None or 'expire' not in cfg:
            return True
        expire = datetime.strptime(cfg['expire'], "%Y-%m-%d")
        return expire <= datetime.now()

sysadmin/forms.py
from django import forms
from db.models import *


class BaseForm(forms.Form):
    pass


class ServerForm(BaseForm):
    hostname = forms.CharField(required=True)
    ip = forms.GenericIPAddressField(required=True)
    status = forms.CharField(required=True)
    port = forms.IntegerField(required=True)
    encryption = forms.CharField(required=True)
    comments = forms.CharField(required=False, widget=forms.Textarea)

    def clean_status(self):
        status = self.cleaned_data['status']
        s = Server()
        if status not in s.STATUS:
            raise forms.ValidationError("Invalid status")
        return status

    def clean_encryption(self):
        value = self.cleaned_data['encryption']
        s = Server()
        if value not in s.ENCRYPTION_METHODS:
            raise forms.ValidationError("Invalid encryption")
        return value

    def clean_port(self):
        port = self.cleaned_data['port']
        if port > 65535 and port < 1:
            raise forms.ValidationError("Invalid port number")
        return port

sysadmin/controllers/download.py
from sysadmin.views import *


@login_required
@load_license
@active_page("download")
def index(request):
    return render(request, "sysadmin/download/index.html", {})

sysadmin/controllers/license.py
from sysadmin.views import *


@login_required
@load_license
@active_page("license")
def index(request):
    license = License.get()
    if license is None:
        license = License.initial()
    data = {
        "license": license,
        "config": license.get_config(),
    }
    return render(request, "sysadmin/license/index.html", data)


@login_required
@load_license
@require_POST
def update(request):
    if "license" not in request.POST:
        return render_400("Require license parameter")
    license = License.get()
    license.license = request.POST['license']
    license.save()
    log_request(request, "license", "Update license")
    return render_200("OK")

sysadmin/controllers/login.py
from django.db import connections
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.utils.translation import ugettext as _

from sysadmin.views import *


# Return format:
# [
#   [{USER Object}, {inbound flow}, {outbound flow}]
#   ...
# ]
def calculate_top_flow_usage(start_date, limit):
    date_str = start_date.strftime("%Y-%m-%d %H:%M:%S")
    sql = "SELECT userid, SUM(inbound_flow) AS `inbound`, SUM(outbound_flow) AS `outbound` FROM flow_statistic WHERE date > '%s' GROUP BY userid ORDER BY outbound DESC LIMIT %d" % (date_str, limit)
    row_ret = []
    user_ids = []
    with connections['monitor'].cursor() as cursor:
        cursor.execute(sql)
        for row in cursor.fetchall():
            row_ret.append(row)
            user_ids.append(row[0])

    udict = {}
    for user in SSUser.objects.filter(userid__in=user_ids):
        udict[user.userid] = user

    ret = []
    for item in row_ret:
        if item[0] not in udict:
            continue
        ret.append([udict[item[0]], item[1], item[2]])
    return ret


# Return format:
# [
#   [{USER Object}, {inbound bandwidth}, {outbound bandwidth}]
#   ...
# ]
def calculate_top_bandwidth_usage(start_date, limit):
    date_str = start_date.strftime("%Y-%m-%d %H:%M:%S")
    sql = "SELECT userid, MAX(inbound_bandwidth) AS `inbound`, MAX(outbound_bandwidth) AS `outbound` FROM flow_statistic WHERE date > '%s' GROUP BY userid ORDER BY outbound DESC LIMIT %d " % (date_str, limit)
    row_ret = []
    user_ids = []
    with connections['monitor'].cursor() as cursor:
        cursor.execute(sql)
        for row in cursor.fetchall():
            row_ret.append(row)
            user_ids.append(row[0])

    udict = {}
    for user in SSUser.objects.filter(userid__in=user_ids):
        udict[user.userid] = user

    ret = []
    for item in row_ret:
        if item[0] not in udict:
            continue
        ret.append([udict[item[0]], item[1], item[2]])
    return ret


def calculate_count_and_total_bandwidth():
    sql = "SELECT COUNT(id) as `number`, SUM(bandwidth) as `bandwidth` FROM user WHERE status='Enabled'"
    count, bandwidth = 0, 0
    with connections['default'].cursor() as cursor:
        cursor.execute(sql)
        for row in cursor.fetchall():
            count = row[0]
            bandwidth = row[1]
            break
    return count, bandwidth


@login_required
@load_license
def total_bandwidth(request):
    start_date = datetime.now() - timedelta(days=1)
    date_str = start_date.strftime("%Y-%m-%d %H:%M:%S")
    sql = "SELECT date, SUM(inbound_bandwidth) AS `inbound`, SUM(outbound_bandwidth) AS `outbound` FROM flow_statistic WHERE date > '%s' GROUP BY date" % date_str
    ret = [[], []]
    with connections['monitor'].cursor() as cursor:
        cursor.execute(sql)
        for row in cursor.fetchall():
            dstr = row[0].strftime("%Y-%m-%d %H:%M")
            ret[0].append([dstr, int(row[1])])
            ret[1].append([dstr, int(row[2])])
    return render_json(ret)


@login_required
@load_license
@active_page('dashboard')
def index(request):
    start_date = datetime.now() - timedelta(days=1)
    count, bw = calculate_count_and_total_bandwidth()
    data = {
        "number_customers": count,
        "number_servers": Server.objects.count(),
        "total_bandwidth": bw,
        "top_10_flow_user": calculate_top_flow_usage(start_date, 10),
        "top_10_bandwidth_user": calculate_top_bandwidth_usage(start_date, 10),
    }
    return render(request, 'sysadmin/login/index.html', data)


def login_index(request):
    if request.user.is_authenticated():
        return redirect("/admin")
    return render(request, 'sysadmin/login/login.html', {})


def do_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return redirect("/admin")
    return render(request, 'sysadmin/login/login.html', {'error_message': _('Login Error')})


@login_required
def do_logout(request):
    logout(request)
    return redirect("/admin/login")


@login_required
@require_POST
def change_password(request):
    password = request.POST['password']
    confirm = request.POST['confirm']
    if password != confirm:
        return render_json({'confirm': _("Confirm is not equals to password")}, 400)
    user = request.user
    user.set_password(password)
    user.save()
    update_session_auth_hash(request, user)
    return render_200("OK")

templates/sysadmin/servers/detail_modal.html
<div id="server-detail-modal" class="modal fade" role="dialog">
  <div class="modal-dialog" role="document" style="width: 750px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel">{% t "Server" %}: <span id="server-detail-hostname"></span></h4>
      </div>
      <div class="modal-body">
        <div class="row"><!-- chart-row -->
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <i class="fa fa-bar-chart-o"></i>
                      <h3 class="box-title">{% t "Bandwidth" %}</h3>
                    </div>
                    <div class="box-body">
                        <div id="server-detail-bandwidth-chart" style="height: 200px;"></div>
                    </div>
                </div>
            </div>
        </div><!-- /.chart-row -->
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% t "Close" %}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/sysadmin/servers/index.html
{% extends "sysadmin/layout/master.html" %}
{% block content %}
<section class="content-header">
    <h1>{% t "Servers" %}</h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
        {% csrf_token %}
        <div class="box box-primary">
          <div class="box-header with-border">
              <h3 class="box-title">{% t "Server List" %}</h3>
            <div class="box-tools">
              <form method="GET">
              <div class="input-group input-group-sm" style="width: 200px;">
                <div class="input-group-btn">
                    {% if exceed %}
                    <span post-url="/admin/servers/create" class="btn btn-primary disabled"><b>{% t "Create" %}</b></span>
                    {% else %}
                    <span post-url="/admin/servers/create" class="btn btn-primary" onclick="return create_server(this);"><b>{% t "Create" %}</b></span>
                    {% endif %}
                </div>
                <input type="text" name="search" class="form-control pull-right" placeholder="{% t "Search" %}" value="{{search}}">
                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
              </form>
            </div>
          </div>
          <div class="box-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                    <th>{% t "Hostname" %}</th>
                    <th>{% t "IP" %}</th>
                    <th>{% t "Status" %}</th>
                    <th>{% t "Encryption" %}</th>
                    <th>{% t "Customers" %}</th>
                    <th>{% t "Comments" %}</th>
                    <th>{% t "Created At" %}</th>
                    <th>{% t "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for server in servers %}
                <tr>
                    <td><a href="#" onclick="show_server_detail(this);" data-id="{{server.id}}" data-hostname="{{server.hostname}}">{{server.hostname}}</a></td>
                  <td>{{server.ip}}:{{server.port}}</td>
                  <td>
                    {% if server.status == "Enabled" %}
                    <span class="badge bg-green">{% t server.status %}</span>
                    {% elif server.status == "Full" %}
                    <span class="badge bg-yellow">{% t server.status %}</span>
                    {% else %}
                    <span class="badge bg-red">{% t server.status %}</span>
                    {% endif %}
                  </td>
                  <td>{{server.encryption|upper}}</td>
                  <td>{{server.ssuser_set.count}}</td>
                  <td>{{server.comments}}</td>
                  <td>{{server.created_at|fdate}}</td>
                  <td>
                      <span post-url="/admin/servers/{{server.id}}/edit" data-id="{{server.id}}" class="btn btn-primary btn-xs" onclick="return edit_server(this);">{% t "Edit" %}</span>
                      <a href="/admin/servers/{{server.id}}/delete" class="btn btn-danger btn-xs" onclick="return double_check(this);" data-confirm="{% t "Are you sure to delete?" %}">{% t "Delete" %}</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="box-footer clearfix">
            {% paginate servers request %}
          </div>
        </div>
    </div>
  </div>
</section>

<div id="server-modal" class="modal fade" role="dialog" data-msgcreate="{% t "Create Server" %}" data-msgedit="{% t "Edit Server" %}">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="server-modal-title">{% t "Create Server" %}</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
          <div class="box-body">
            <div class="form-group">
                <label for="server-hostname" class="col-sm-2 control-label">{% t "Hostname" %}</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" id="server-hostname" placeholder="{% t "Hostname" %}">
              </div>
            </div>
            <div class="form-group">
                <label for="server-ip" class="col-sm-2 control-label">{% t "IP" %}</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" id="server-ip" placeholder="{% t "IP" %}">
              </div>
            </div>
            <div class="form-group">
                <label for="server-port" class="col-sm-2 control-label">{% t "Port" %}</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" id="server-port" placeholder="{% t "Port" %}">
              </div>
            </div>
            <div class="form-group">
                <label for="server-status" class="col-sm-2 control-label">{% t "Status" %}</label>
              <div class="col-sm-10">
                <select id="server-status" class="form-control">
                    <option value="Enabled">{% t "Enabled" %}</option>
                    <option value="Full">{% t "Full" %}</option>
                    <option value="Disabled">{% t "Disabled" %}</option>
                </select>
              </div>
            </div>
            <div class="form-group">
                <label for="server-encryption" class="col-sm-2 control-label">{% t "Encryption Method" %}</label>
              <div class="col-sm-10">
                <select id="server-encryption" class="form-control">
                    <option value="aes-128-cfb">AES-128-CFB</option>
                    <option value="aes-192-cfb">AES-192-CFB</option>
                    <option value="aes-256-cfb">AES-256-CFB</option>
                    <option value="rc4-md5">RC4-MD5</option>
                </select>
              </div>
            </div>
            <div class="form-group">
                <label for="server-comments" class="col-sm-2 control-label">{% t "Comments" %}</label>

              <div class="col-sm-10">
                  <input type="text" class="form-control" id="server-comments" placeholder="{% t "Comments" %}">
              </div>
            </div>

          </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% t "Close" %}</button>
          <button type="button" class="btn btn-primary" id="server-modal-submit">{% t "Save" %}</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include "sysadmin/servers/detail_modal.html" %}
{% endblock %}